// Code generated by "go run ./internal/plugin/gen"; DO NOT EDIT.
//
// One concrete type per capability combination a plugin can declare. See
// gen/main.go for why these are generated rather than written by hand, and
// driver.go for what each ops struct does.

package plugin

import "github.com/brf-tech/filex/backend/internal/storage"

type (
	drvR struct {
		*readOps
	}
	drvRW struct {
		*readOps
		*watchOps
	}
	drvRP struct {
		*readOps
		*presignOps
	}
	drvRWP struct {
		*readOps
		*watchOps
		*presignOps
	}
	drvX struct {
		*readOps
		*writeOps
	}
	drvXT struct {
		*readOps
		*writeOps
		*touchOps
	}
	drvXW struct {
		*readOps
		*writeOps
		*watchOps
	}
	drvXTW struct {
		*readOps
		*writeOps
		*touchOps
		*watchOps
	}
	drvXP struct {
		*readOps
		*writeOps
		*presignOps
	}
	drvXTP struct {
		*readOps
		*writeOps
		*touchOps
		*presignOps
	}
	drvXWP struct {
		*readOps
		*writeOps
		*watchOps
		*presignOps
	}
	drvXTWP struct {
		*readOps
		*writeOps
		*touchOps
		*watchOps
		*presignOps
	}
	drvXM struct {
		*readOps
		*writeOps
		*multipartOps
	}
	drvXTM struct {
		*readOps
		*writeOps
		*touchOps
		*multipartOps
	}
	drvXWM struct {
		*readOps
		*writeOps
		*watchOps
		*multipartOps
	}
	drvXTWM struct {
		*readOps
		*writeOps
		*touchOps
		*watchOps
		*multipartOps
	}
	drvXPM struct {
		*readOps
		*writeOps
		*presignOps
		*multipartOps
	}
	drvXTPM struct {
		*readOps
		*writeOps
		*touchOps
		*presignOps
		*multipartOps
	}
	drvXWPM struct {
		*readOps
		*writeOps
		*watchOps
		*presignOps
		*multipartOps
	}
	drvXTWPM struct {
		*readOps
		*writeOps
		*touchOps
		*watchOps
		*presignOps
		*multipartOps
	}
)

var (
	_ storage.Driver       = drvR{}
	_ storage.RangeReader  = drvR{}
	_ storage.Driver       = drvRW{}
	_ storage.RangeReader  = drvRW{}
	_ storage.Watcher      = drvRW{}
	_ storage.Driver       = drvRP{}
	_ storage.RangeReader  = drvRP{}
	_ storage.Presigner    = drvRP{}
	_ storage.Driver       = drvRWP{}
	_ storage.RangeReader  = drvRWP{}
	_ storage.Watcher      = drvRWP{}
	_ storage.Presigner    = drvRWP{}
	_ storage.Driver       = drvX{}
	_ storage.RangeReader  = drvX{}
	_ storage.Writer       = drvX{}
	_ storage.Deleter      = drvX{}
	_ storage.Mover        = drvX{}
	_ storage.Copier       = drvX{}
	_ storage.Mkdirer      = drvX{}
	_ storage.Driver       = drvXT{}
	_ storage.RangeReader  = drvXT{}
	_ storage.Writer       = drvXT{}
	_ storage.Deleter      = drvXT{}
	_ storage.Mover        = drvXT{}
	_ storage.Copier       = drvXT{}
	_ storage.Mkdirer      = drvXT{}
	_ storage.Toucher      = drvXT{}
	_ storage.Driver       = drvXW{}
	_ storage.RangeReader  = drvXW{}
	_ storage.Writer       = drvXW{}
	_ storage.Deleter      = drvXW{}
	_ storage.Mover        = drvXW{}
	_ storage.Copier       = drvXW{}
	_ storage.Mkdirer      = drvXW{}
	_ storage.Watcher      = drvXW{}
	_ storage.Driver       = drvXTW{}
	_ storage.RangeReader  = drvXTW{}
	_ storage.Writer       = drvXTW{}
	_ storage.Deleter      = drvXTW{}
	_ storage.Mover        = drvXTW{}
	_ storage.Copier       = drvXTW{}
	_ storage.Mkdirer      = drvXTW{}
	_ storage.Toucher      = drvXTW{}
	_ storage.Watcher      = drvXTW{}
	_ storage.Driver       = drvXP{}
	_ storage.RangeReader  = drvXP{}
	_ storage.Writer       = drvXP{}
	_ storage.Deleter      = drvXP{}
	_ storage.Mover        = drvXP{}
	_ storage.Copier       = drvXP{}
	_ storage.Mkdirer      = drvXP{}
	_ storage.Presigner    = drvXP{}
	_ storage.Driver       = drvXTP{}
	_ storage.RangeReader  = drvXTP{}
	_ storage.Writer       = drvXTP{}
	_ storage.Deleter      = drvXTP{}
	_ storage.Mover        = drvXTP{}
	_ storage.Copier       = drvXTP{}
	_ storage.Mkdirer      = drvXTP{}
	_ storage.Toucher      = drvXTP{}
	_ storage.Presigner    = drvXTP{}
	_ storage.Driver       = drvXWP{}
	_ storage.RangeReader  = drvXWP{}
	_ storage.Writer       = drvXWP{}
	_ storage.Deleter      = drvXWP{}
	_ storage.Mover        = drvXWP{}
	_ storage.Copier       = drvXWP{}
	_ storage.Mkdirer      = drvXWP{}
	_ storage.Watcher      = drvXWP{}
	_ storage.Presigner    = drvXWP{}
	_ storage.Driver       = drvXTWP{}
	_ storage.RangeReader  = drvXTWP{}
	_ storage.Writer       = drvXTWP{}
	_ storage.Deleter      = drvXTWP{}
	_ storage.Mover        = drvXTWP{}
	_ storage.Copier       = drvXTWP{}
	_ storage.Mkdirer      = drvXTWP{}
	_ storage.Toucher      = drvXTWP{}
	_ storage.Watcher      = drvXTWP{}
	_ storage.Presigner    = drvXTWP{}
	_ storage.Driver       = drvXM{}
	_ storage.RangeReader  = drvXM{}
	_ storage.Writer       = drvXM{}
	_ storage.Deleter      = drvXM{}
	_ storage.Mover        = drvXM{}
	_ storage.Copier       = drvXM{}
	_ storage.Mkdirer      = drvXM{}
	_ storage.PartUploader = drvXM{}
	_ storage.Driver       = drvXTM{}
	_ storage.RangeReader  = drvXTM{}
	_ storage.Writer       = drvXTM{}
	_ storage.Deleter      = drvXTM{}
	_ storage.Mover        = drvXTM{}
	_ storage.Copier       = drvXTM{}
	_ storage.Mkdirer      = drvXTM{}
	_ storage.Toucher      = drvXTM{}
	_ storage.PartUploader = drvXTM{}
	_ storage.Driver       = drvXWM{}
	_ storage.RangeReader  = drvXWM{}
	_ storage.Writer       = drvXWM{}
	_ storage.Deleter      = drvXWM{}
	_ storage.Mover        = drvXWM{}
	_ storage.Copier       = drvXWM{}
	_ storage.Mkdirer      = drvXWM{}
	_ storage.Watcher      = drvXWM{}
	_ storage.PartUploader = drvXWM{}
	_ storage.Driver       = drvXTWM{}
	_ storage.RangeReader  = drvXTWM{}
	_ storage.Writer       = drvXTWM{}
	_ storage.Deleter      = drvXTWM{}
	_ storage.Mover        = drvXTWM{}
	_ storage.Copier       = drvXTWM{}
	_ storage.Mkdirer      = drvXTWM{}
	_ storage.Toucher      = drvXTWM{}
	_ storage.Watcher      = drvXTWM{}
	_ storage.PartUploader = drvXTWM{}
	_ storage.Driver       = drvXPM{}
	_ storage.RangeReader  = drvXPM{}
	_ storage.Writer       = drvXPM{}
	_ storage.Deleter      = drvXPM{}
	_ storage.Mover        = drvXPM{}
	_ storage.Copier       = drvXPM{}
	_ storage.Mkdirer      = drvXPM{}
	_ storage.Presigner    = drvXPM{}
	_ storage.PartUploader = drvXPM{}
	_ storage.Driver       = drvXTPM{}
	_ storage.RangeReader  = drvXTPM{}
	_ storage.Writer       = drvXTPM{}
	_ storage.Deleter      = drvXTPM{}
	_ storage.Mover        = drvXTPM{}
	_ storage.Copier       = drvXTPM{}
	_ storage.Mkdirer      = drvXTPM{}
	_ storage.Toucher      = drvXTPM{}
	_ storage.Presigner    = drvXTPM{}
	_ storage.PartUploader = drvXTPM{}
	_ storage.Driver       = drvXWPM{}
	_ storage.RangeReader  = drvXWPM{}
	_ storage.Writer       = drvXWPM{}
	_ storage.Deleter      = drvXWPM{}
	_ storage.Mover        = drvXWPM{}
	_ storage.Copier       = drvXWPM{}
	_ storage.Mkdirer      = drvXWPM{}
	_ storage.Watcher      = drvXWPM{}
	_ storage.Presigner    = drvXWPM{}
	_ storage.PartUploader = drvXWPM{}
	_ storage.Driver       = drvXTWPM{}
	_ storage.RangeReader  = drvXTWPM{}
	_ storage.Writer       = drvXTWPM{}
	_ storage.Deleter      = drvXTWPM{}
	_ storage.Mover        = drvXTWPM{}
	_ storage.Copier       = drvXTWPM{}
	_ storage.Mkdirer      = drvXTWPM{}
	_ storage.Toucher      = drvXTWPM{}
	_ storage.Watcher      = drvXTWPM{}
	_ storage.Presigner    = drvXTWPM{}
	_ storage.PartUploader = drvXTWPM{}
)

// newShape returns the concrete driver type whose method set matches caps
// exactly. The switch is exhaustive over the same combinations the type list
// above declares, so a capability set can never fall through to a shape that
// offers more than the plugin promised.
func newShape(r *readOps, x *writeOps, t *touchOps, w *watchOps, p *presignOps, m *multipartOps, caps Capabilities) storage.Driver {
	write := caps.Writable()
	switch {
	case write && caps.SetMtime && caps.Watch && caps.Presign && caps.Multipart:
		return drvXTWPM{r, x, t, w, p, m}
	case write && !caps.SetMtime && caps.Watch && caps.Presign && caps.Multipart:
		return drvXWPM{r, x, w, p, m}
	case write && caps.SetMtime && !caps.Watch && caps.Presign && caps.Multipart:
		return drvXTPM{r, x, t, p, m}
	case write && !caps.SetMtime && !caps.Watch && caps.Presign && caps.Multipart:
		return drvXPM{r, x, p, m}
	case write && caps.SetMtime && caps.Watch && !caps.Presign && caps.Multipart:
		return drvXTWM{r, x, t, w, m}
	case write && !caps.SetMtime && caps.Watch && !caps.Presign && caps.Multipart:
		return drvXWM{r, x, w, m}
	case write && caps.SetMtime && !caps.Watch && !caps.Presign && caps.Multipart:
		return drvXTM{r, x, t, m}
	case write && !caps.SetMtime && !caps.Watch && !caps.Presign && caps.Multipart:
		return drvXM{r, x, m}
	case write && caps.SetMtime && caps.Watch && caps.Presign && !caps.Multipart:
		return drvXTWP{r, x, t, w, p}
	case write && !caps.SetMtime && caps.Watch && caps.Presign && !caps.Multipart:
		return drvXWP{r, x, w, p}
	case write && caps.SetMtime && !caps.Watch && caps.Presign && !caps.Multipart:
		return drvXTP{r, x, t, p}
	case write && !caps.SetMtime && !caps.Watch && caps.Presign && !caps.Multipart:
		return drvXP{r, x, p}
	case write && caps.SetMtime && caps.Watch && !caps.Presign && !caps.Multipart:
		return drvXTW{r, x, t, w}
	case write && !caps.SetMtime && caps.Watch && !caps.Presign && !caps.Multipart:
		return drvXW{r, x, w}
	case write && caps.SetMtime && !caps.Watch && !caps.Presign && !caps.Multipart:
		return drvXT{r, x, t}
	case write && !caps.SetMtime && !caps.Watch && !caps.Presign && !caps.Multipart:
		return drvX{r, x}
	case !write && !caps.SetMtime && caps.Watch && caps.Presign && !caps.Multipart:
		return drvRWP{r, w, p}
	case !write && !caps.SetMtime && !caps.Watch && caps.Presign && !caps.Multipart:
		return drvRP{r, p}
	case !write && !caps.SetMtime && caps.Watch && !caps.Presign && !caps.Multipart:
		return drvRW{r, w}
	case !write && !caps.SetMtime && !caps.Watch && !caps.Presign && !caps.Multipart:
		return drvR{r}
	}
	// Unreachable: the cases above cover every combination.
	return drvR{r}
}
