"""Regenerate stream-vectors.json with an INDEPENDENT implementation.

The vectors pin the STREAM content format, the 0x02 folder file and the
single encrypted file (.fxe) of docs/E2E-ENCRYPTION.md ("Streaming content",
"Single encrypted files", "Format reference") to Python `cryptography`'s
AESGCM, PBKDF2HMAC and HKDF, which are neither the WebCrypto code in
packages/core/src/lib/e2estream.ts + e2efile.ts nor the Go code in this
package. Both of those are tested against this file, so a mistake the two of
them share (they were written by the same hand) still fails.

    python backend/internal/e2edecrypt/testdata/gen_stream_vectors.py

Requires `pip install cryptography` (>= 42). The output is deterministic:
every key, IV and nonce prefix below is fixed.
"""
import base64
import hashlib
import json
import os
import struct

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC

KEY = bytes(range(32))
PREFIX = bytes([0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6])
TAG = 16


def pattern(n: int, seed: int) -> bytes:
    return bytes(((i * 31 + seed) & 0xFF) for i in range(n))


def nonce(prefix: bytes, i: int, last: bool) -> bytes:
    return prefix + struct.pack(">I", i) + (b"\x01" if last else b"\x00")


def stream_encrypt(key: bytes, prefix: bytes, plain: bytes, log2: int) -> bytes:
    size = 1 << log2
    chunks = [plain[i : i + size] for i in range(0, len(plain), size)] or [b""]
    g = AESGCM(key)
    out = b""
    for i, c in enumerate(chunks):
        out += g.encrypt(nonce(prefix, i, i == len(chunks) - 1), c, None)
    return out


def b64(b: bytes) -> str:
    return base64.b64encode(b).decode("ascii")


def seal(key: bytes, iv: bytes, plain: bytes) -> str:
    return b64(iv + AESGCM(key).encrypt(iv, plain, None))


def crockford(raw: bytes) -> str:
    alphabet = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
    bits = "".join(f"{x:08b}" for x in raw)
    chars = "".join(alphabet[int(bits[i : i + 5], 2)] for i in range(0, len(bits), 5))
    return "-".join(chars[i : i + 4] for i in range(0, len(chars), 4))


# ── STREAM on its own ─────────────────────────────────────────────────
cases = []
for log2, n, seed in [
    (10, 0, 1),
    (10, 1, 2),
    (10, 1023, 3),
    (10, 1024, 4),
    (10, 1025, 5),
    (10, 2048, 6),
    (10, 3000, 7),
    (20, 0, 8),
    (20, 5, 9),
    (20, (1 << 20) + 5, 10),
    (20, 2 << 20, 11),
]:
    ct = stream_encrypt(KEY, PREFIX, pattern(n, seed), log2)
    row = {"log2": log2, "len": n, "seed": seed, "ct_len": len(ct), "ct_sha256": hashlib.sha256(ct).hexdigest()}
    if len(ct) <= 4096:
        row["ct_hex"] = ct.hex()
    cases.append(row)

# ── a folder file, header version 0x02 ────────────────────────────────
FMK = bytes(range(100, 132))
DEK = bytes(range(200, 232))
WRAP_IV = bytes(range(1, 13))
V2_PREFIX = bytes([0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6])
V2_LOG2 = 10
V2_LEN, V2_SEED = 2600, 12
wrapped = AESGCM(FMK).encrypt(WRAP_IV, DEK, None)
header = b"filexe2e" + b"\x02" + WRAP_IV + wrapped + V2_PREFIX + bytes([V2_LOG2]) + bytes(20)
assert len(header) == 97
v2_file = header + stream_encrypt(DEK, V2_PREFIX, pattern(V2_LEN, V2_SEED), V2_LOG2)

# ── a single encrypted file (.fxe) ────────────────────────────────────
PASSWORD = "vector password, not a real one"
ITER = 1000  # readers accept 1 … 100 000 000; writers use 600 000
SALT = bytes(range(16))
RK_RAW = bytes(range(50, 70))
RK_SALT = bytes(range(70, 86))
FXE_FMK = bytes(range(10, 42))
FXE_DEK = bytes(range(42, 74))
FXE_PREFIX = bytes([0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6])
FXE_LOG2 = 10
FXE_LEN, FXE_SEED = 2500, 13
FXE_NAME = "Bütçe 2027 — İzmir.pdf"
kek = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=SALT, iterations=ITER).derive(PASSWORD.encode("utf-8"))
rkek = HKDF(algorithm=hashes.SHA256(), length=32, salt=RK_SALT, info=b"filex-e2e-recovery-v1").derive(RK_RAW)
fxe_header = {
    "salt": b64(SALT),
    "iter": ITER,
    "verify": seal(kek, bytes([1] * 12), b"filex-e2e-verify-v1"),
    "fmk": "wrapped",
    "fmk_pw": seal(kek, bytes([2] * 12), FXE_FMK),
    "rk": {"salt": b64(RK_SALT), "blob": seal(rkek, bytes([3] * 12), FXE_FMK)},
    "dek": seal(FXE_FMK, bytes([4] * 12), FXE_DEK),
    "name": seal(FXE_FMK, bytes([5] * 12), FXE_NAME.encode("utf-8")),
    "chunk": FXE_LOG2,
    "nonce": b64(FXE_PREFIX),
    "size": FXE_LEN,
    "x_future": {"kept": True},
}
hjson = json.dumps(fxe_header, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
fxe_file = b"filexfxe" + b"\x01" + struct.pack(">I", len(hjson)) + hjson
fxe_file += stream_encrypt(FXE_DEK, FXE_PREFIX, pattern(FXE_LEN, FXE_SEED), FXE_LOG2)

out = {
    "comment": "STREAM / 0x02 / .fxe vectors, generated by gen_stream_vectors.py with Python cryptography. Do not edit by hand.",
    "key_hex": KEY.hex(),
    "prefix_hex": PREFIX.hex(),
    "plaintext": "byte i of a plaintext is (i*31 + seed) & 0xff",
    "stream": cases,
    "folder_v2": {
        "fmk_hex": FMK.hex(),
        "len": V2_LEN,
        "seed": V2_SEED,
        "file_hex": v2_file.hex(),
    },
    "fxe": {
        "password": PASSWORD,
        "recovery_key": crockford(RK_RAW),
        "name": FXE_NAME,
        "len": FXE_LEN,
        "seed": FXE_SEED,
        "file_hex": fxe_file.hex(),
    },
}

here = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(here, "stream-vectors.json"), "w", encoding="utf-8", newline="\n") as f:
    json.dump(out, f, indent=2, ensure_ascii=False)
    f.write("\n")
