"""Regenerate name-vectors.json with an INDEPENDENT AES-SIV implementation.

The vectors pin encrypted file names (docs/E2E-ENCRYPTION.md, "Encrypted
names") to Python `cryptography`'s AESSIV, which is neither the WebCrypto
code in packages/core/src/lib/aessiv.ts nor the Go code in this package.
Both of those are tested against this file, so a mistake shared by the two
of them (they were written by the same hand) still fails.

    python backend/internal/e2edecrypt/testdata/gen_name_vectors.py

Requires `pip install cryptography` (>= 42). The output is deterministic.

Layout (docs/E2E-ENCRYPTION.md → "Folder ids"):
  - a name is sealed with AES-SIV, associated data = [id of the folder it is in]
  - a folder's id is 16 bytes, fixed when the folder first gets its
    encrypted name and carried in it from then on: the root's and a new
    folder's are random; a folder whose name was never encrypted has
    SIV-V(name, AD = [parent id, "filex-e2e-dir-id"]), the 16-byte synthetic
    IV — the only kind a vector can pin, and the one these vectors use
  - a file is stored as S, a folder as S.D (D = base64url of its id)
  - S longer than the threshold (a folder counts the ".D" too) → H.fxl (file)
    or H.fxl.D (folder), H = base64url(SHA-256(S)), sidecar H.fxl.name = S
"""
import base64
import hashlib
import json
import os
import unicodedata

from cryptography.hazmat.primitives.ciphers.aead import AESSIV

LONG = 220
KEY = bytes(range(64))
ROOT_ID = bytes(range(100, 116))
DIR_ID_LABEL = b"filex-e2e-dir-id"


def b64url(b: bytes) -> str:
    return base64.urlsafe_b64encode(b).rstrip(b"=").decode("ascii")


def nfc(s: str) -> bytes:
    return unicodedata.normalize("NFC", s).encode("utf-8")


def dir_id(name: str, parent: bytes) -> bytes:
    return AESSIV(KEY).encrypt(nfc(name), [parent, DIR_ID_LABEL])[:16]


def enc(name: str, parent: bytes, is_dir: bool) -> dict:
    s = b64url(AESSIV(KEY).encrypt(nfc(name), [parent]))
    row = {
        "name": unicodedata.normalize("NFC", name),
        "parent_id": b64url(parent),
        "dir": is_dir,
        "encoded": s,
    }
    suffix = ""
    if is_dir:
        d = dir_id(name, parent)
        row["dir_id"] = b64url(d)
        suffix = "." + b64url(d)
    if len(s) + len(suffix) <= LONG:
        row["stored"] = s + suffix
    else:
        h = b64url(hashlib.sha256(s.encode("ascii")).digest())
        row["stored"] = h + ".fxl" + suffix
        row["sidecar"] = h + ".fxl.name"
    return row


FILES = [
    "a",
    "Rapor.docx",
    "15 bytes long.x",
    "exactly16bytes!!",
    "17 bytes long..xy",
    "İzmir notları — 2026.txt",
    "ŞĞÜÖÇı şğüöç",
    "🔒 kasa",
    ".gitignore",
    "a" * 149,
    "a" * 150,
    "ş" * 120,
]

vectors = [enc(n, ROOT_ID, False) for n in FILES]

# Folders under the root, and a chain: Sözleşmeler / 2024 / fatura.pdf — the
# same "fatura.pdf" under 2025 must come out different.
soz = enc("Sözleşmeler", ROOT_ID, True)
vectors.append(soz)
soz_id = dir_id("Sözleşmeler", ROOT_ID)
y24 = enc("2024", soz_id, True)
y25 = enc("2025", soz_id, True)
vectors += [y24, y25]
vectors.append(enc("fatura.pdf", dir_id("2024", soz_id), False))
vectors.append(enc("fatura.pdf", dir_id("2025", soz_id), False))
# Folder names either side of the threshold: a folder counts its ".D"
# (23 chars), so 131 bytes still fit (196 + 23 = 219) and 132 do not.
vectors.append(enc("K" * 131, ROOT_ID, True))
vectors.append(enc("K" * 132, ROOT_ID, True))

out = {
    "comment": "AES-256-SIV (RFC 5297) name vectors with folder ids, generated by gen_name_vectors.py with Python cryptography AESSIV. Do not edit by hand.",
    "key_hex": KEY.hex(),
    "root_id": b64url(ROOT_ID),
    "dir_id_label": DIR_ID_LABEL.decode("ascii"),
    "long": LONG,
    "rfc5297_a1": {
        "key_hex": "fffefdfcfbfaf9f8f7f6f5f4f3f2f1f0f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff",
        "ad_hex": "101112131415161718191a1b1c1d1e1f2021222324252627",
        "plaintext_hex": "112233445566778899aabbccddee",
        "output_hex": "85632d07c6e8f37f950acd320a2ecc9340c02b9690c4dc04daef7f6afe5c",
    },
    "vectors": vectors,
}
here = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(here, "name-vectors.json"), "w", encoding="utf-8", newline="\n") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)
    f.write("\n")
print("wrote", len(vectors), "vectors")
