// What "recovery" is allowed to cost — and the one thing it may never cost.
//
// Folder recovery adds two more ways to reach an encrypted folder's key: a
// user recovery key shown once at creation, and an optional operator escrow
// key. The dangerous part is not the new paths, it is the old data: every
// folder already out there was created under the v1 marker, where the DEK is
// wrapped by the password KEK directly. If this change ever stops opening
// one of those, nothing else in it matters.
//
// So the first suite here does not test the new feature at all. It encrypts
// with the ACTUAL v0.30.1 module (frozen at tests/fixtures/, taken from the
// release commit) and decrypts with the current one, in both directions.
//
// The escrow suite uses a keypair generated by the Go CLI
// (`filex e2e-escrow keygen`), not one minted in-process, because the claim
// under test is Go-to-WebCrypto interoperability. A keypair WebCrypto
// generated for itself would prove nothing about the half the operator gets.

import { beforeAll, describe, expect, it } from 'vitest';

import {
  E2E_MARKER_VERSION,
  createMarker,
  E2E_MIN_ITERATIONS,
  createEncryptedFolder,
  decryptFile,
  encryptFile,
  addEscrowSlot,
  declineEscrowSlot,
  escrowAvailability,
  escrowKeyId,
  escrowOfferState,
  formatRecoveryKey,
  generateRecoveryKey,
  importEscrowPrivateKey,
  markerHasEscrow,
  markerHasRecovery,
  parseMarker,
  parseRecoveryKey,
  unlockWithEscrowKey,
  unlockWithPassword,
  unlockWithRecoveryKey,
  upgradeMarkerV1,
  type E2eMarker,
} from '../../../packages/core/src/lib/e2ecrypto';

import * as legacy from '../fixtures/e2ecrypto-legacy-v0.30.1';
import escrowTestKey from '../fixtures/escrow-testkey.json';

const PW = 'correct horse battery';
const enc = new TextEncoder();
const dec = new TextDecoder();

/** Round-trip a marker through JSON, the way it actually travels: the client
 *  uploads it as a file and reads it back with parseMarker. A field that
 *  survives in memory but not on the wire is not a field. */
function wire(m: E2eMarker): E2eMarker {
  const parsed = parseMarker(JSON.stringify(m));
  if (!parsed) throw new Error('marker did not survive parseMarker');
  return parsed;
}

const SLOW = 30_000;

// ─────────────────────────────────────────────────────────────────────
// 1. The v1 format keeps working — measured against the real old module
// ─────────────────────────────────────────────────────────────────────

describe('folders created before recovery existed', () => {
  let v1Marker: E2eMarker;
  let v1File: ArrayBuffer;
  const secret = 'a file written by filex v0.30.1';

  beforeAll(async () => {
    // Everything here is produced by the FROZEN module, not by this build.
    const made = await legacy.createMarker(PW);
    v1Marker = wire(made.marker as E2eMarker);
    v1File = await legacy.encryptFile(made.kek, enc.encode(secret).buffer as ArrayBuffer);
  }, SLOW);

  it('is still recognised as a marker', () => {
    expect(v1Marker.v).toBe(1);
    expect(markerHasRecovery(v1Marker)).toBe(false);
    expect(markerHasEscrow(v1Marker)).toBe(false);
  });

  it('opens with its password, and decrypts a file the old code wrote', async () => {
    const fmk = await unlockWithPassword(v1Marker, PW);
    expect(fmk).not.toBeNull();
    expect(dec.decode(await decryptFile(fmk!, v1File))).toBe(secret);
  }, SLOW);

  it('rejects a wrong password without touching the data', async () => {
    expect(await unlockWithPassword(v1Marker, PW + '!')).toBeNull();
  }, SLOW);

  it('accepts a file THIS build writes into it — the format did not drift', async () => {
    const fmk = await unlockWithPassword(v1Marker, PW);
    const fresh = await encryptFile(fmk!, enc.encode('written by the new build').buffer as ArrayBuffer);
    // Decrypted by the OLD module: a v1 folder stays readable by an old tab,
    // an old desktop build, or a rolled-back deployment.
    const legacyKek = await legacy.verifyPassword(v1Marker as never, PW);
    expect(legacyKek).not.toBeNull();
    expect(dec.decode(await legacy.decryptFile(legacyKek!, fresh))).toBe('written by the new build');
  }, SLOW);

  it('is still what THIS build produces when an old embedder calls createMarker', async () => {
    // `createMarker` stays exported and stays v1 so a pinned embedder keeps
    // making folders every build can open. It is also what the browser
    // measurement seeds its "pre-0.31 folder" with, so if this drifts, that
    // measurement quietly stops testing the legacy path.
    const mine = await createMarker(PW);
    expect(mine.marker.v).toBe(1);
    const roundTripped = wire(mine.marker);
    const legacyKek = await legacy.verifyPassword(roundTripped as never, PW);
    expect(legacyKek).not.toBeNull();
    const blob = await encryptFile(mine.kek, enc.encode('seeded').buffer as ArrayBuffer);
    expect(dec.decode(await legacy.decryptFile(legacyKek!, blob))).toBe('seeded');
  }, SLOW);

  it('has no recovery of any kind until someone asks for it', async () => {
    expect(await unlockWithRecoveryKey(v1Marker, generateRecoveryKey())).toBeNull();
    const priv = await importEscrowPrivateKey(escrowTestKey.private_pkcs8_b64);
    expect(await unlockWithEscrowKey(v1Marker, priv)).toBeNull();
  }, SLOW);
});

// ─────────────────────────────────────────────────────────────────────
// 2. The recovery key string
// ─────────────────────────────────────────────────────────────────────

describe('recovery key encoding', () => {
  it('is 160 bits in eight groups of four', () => {
    const k = generateRecoveryKey();
    expect(k).toMatch(/^[0-9A-HJKMNP-TV-Z]{4}(-[0-9A-HJKMNP-TV-Z]{4}){7}$/);
    expect(parseRecoveryKey(k)).toHaveLength(20);
  });

  it('round-trips exact bytes', () => {
    const raw = new Uint8Array(20).map((_, i) => (i * 37 + 11) & 0xff);
    expect(Array.from(parseRecoveryKey(formatRecoveryKey(raw))!)).toEqual(Array.from(raw));
  });

  it('forgives how a human retypes it', () => {
    const raw = crypto.getRandomValues(new Uint8Array(20));
    const k = formatRecoveryKey(raw);
    const mangled = k.toLowerCase().replace(/-/g, ' ');
    expect(Array.from(parseRecoveryKey(mangled)!)).toEqual(Array.from(raw));
  });

  it('maps the Crockford look-alikes rather than failing on them', () => {
    // 0/O and 1/I/L are the pairs a person reading a key aloud confuses.
    const canonical = '0123-4567-89AB-CDEF-GHJK-MNPQ-RSTV-WXYZ';
    const spoken = 'Oi23-4567-89ab-cdef-ghjk-mnpq-rstv-wxyz'.replace('i', 'l');
    expect(Array.from(parseRecoveryKey(spoken)!)).toEqual(Array.from(parseRecoveryKey(canonical)!));
  });

  it('rejects a key of the wrong length or alphabet', () => {
    expect(parseRecoveryKey('')).toBeNull();
    expect(parseRecoveryKey('ABCD-EFGH')).toBeNull();
    expect(parseRecoveryKey('U'.repeat(32))).toBeNull(); // U is not in the alphabet
    expect(parseRecoveryKey('A'.repeat(33))).toBeNull();
  });
});

// ─────────────────────────────────────────────────────────────────────
// 3. A new folder, escrow OFF — the default install
// ─────────────────────────────────────────────────────────────────────

describe('a new encrypted folder with escrow off', () => {
  let marker: E2eMarker;
  let recoveryKey: string;
  let file: ArrayBuffer;
  const secret = 'the quick brown fox';

  beforeAll(async () => {
    const made = await createEncryptedFolder(PW);
    marker = wire(made.marker);
    recoveryKey = made.recoveryKey;
    file = await encryptFile(made.fmk, enc.encode(secret).buffer as ArrayBuffer);
  }, SLOW);

  it('writes a v2 marker with a recovery slot and no escrow slot', () => {
    expect(marker.v).toBe(E2E_MARKER_VERSION);
    expect(marker.fmk).toBe('wrapped');
    expect(marker.iter).toBeGreaterThanOrEqual(E2E_MIN_ITERATIONS);
    expect(markerHasRecovery(marker)).toBe(true);
    expect(markerHasEscrow(marker)).toBe(false);
  });

  it('never puts the password or the recovery key in the marker', () => {
    const json = JSON.stringify(marker);
    expect(json).not.toContain(PW);
    expect(json).not.toContain(recoveryKey);
    expect(json).not.toContain(recoveryKey.replace(/-/g, ''));
  });

  it('opens with the password', async () => {
    const fmk = await unlockWithPassword(marker, PW);
    expect(fmk).not.toBeNull();
    expect(dec.decode(await decryptFile(fmk!, file))).toBe(secret);
  }, SLOW);

  it('opens with the recovery key, and reaches the same master key', async () => {
    const fmk = await unlockWithRecoveryKey(marker, recoveryKey);
    expect(fmk).not.toBeNull();
    // Same bytes out of a file the PASSWORD path encrypted: the two slots are
    // two doors to one key, not two keys that happen to both work today.
    expect(dec.decode(await decryptFile(fmk!, file))).toBe(secret);
  }, SLOW);

  it('rejects a wrong password cleanly', async () => {
    expect(await unlockWithPassword(marker, 'not the password')).toBeNull();
  }, SLOW);

  it('rejects a wrong recovery key cleanly', async () => {
    expect(await unlockWithRecoveryKey(marker, generateRecoveryKey())).toBeNull();
    expect(await unlockWithRecoveryKey(marker, 'not-a-recovery-key')).toBeNull();
  });

  it('CANNOT be opened by the escrow key, even after escrow is switched on', async () => {
    // The whole immutability argument in one assertion. This folder was
    // created while escrow was off, so no escrow-wrapped copy of its master
    // key was ever written. Turning escrow on afterwards changes the server's
    // configuration and nothing about this folder's bytes.
    const priv = await importEscrowPrivateKey(escrowTestKey.private_pkcs8_b64);
    expect(await unlockWithEscrowKey(marker, priv)).toBeNull();
    // And there is nowhere for it to have been hidden.
    expect(JSON.stringify(marker)).not.toContain('esc');
  }, SLOW);
});

// ─────────────────────────────────────────────────────────────────────
// 4. Escrow ON — the operator's second key
// ─────────────────────────────────────────────────────────────────────

describe('a new encrypted folder with escrow on', () => {
  let marker: E2eMarker;
  let recoveryKey: string;
  let file: ArrayBuffer;
  const secret = 'payroll.csv';

  beforeAll(async () => {
    const made = await createEncryptedFolder(PW, {
      escrowPublicKey: escrowTestKey.public_spki_b64,
    });
    marker = wire(made.marker);
    recoveryKey = made.recoveryKey;
    file = await encryptFile(made.fmk, enc.encode(secret).buffer as ArrayBuffer);
  }, SLOW);

  it('names the escrow key it was sealed to', async () => {
    expect(markerHasEscrow(marker)).toBe(true);
    expect(marker.esc!.alg).toBe('RSA-OAEP-256');
    expect(marker.esc!.kid).toBe(await escrowKeyId(escrowTestKey.public_spki_b64));
  });

  it('opens with a PKCS#8 private key the Go CLI generated', async () => {
    const priv = await importEscrowPrivateKey(escrowTestKey.private_pkcs8_b64);
    const fmk = await unlockWithEscrowKey(marker, priv);
    expect(fmk).not.toBeNull();
    expect(dec.decode(await decryptFile(fmk!, file))).toBe(secret);
  }, SLOW);

  it('tolerates PEM armour around the pasted private key', async () => {
    const pem =
      '-----BEGIN PRIVATE KEY-----\n' +
      (escrowTestKey.private_pkcs8_b64.match(/.{1,64}/g) || []).join('\n') +
      '\n-----END PRIVATE KEY-----\n';
    const priv = await importEscrowPrivateKey(pem);
    expect(await unlockWithEscrowKey(marker, priv)).not.toBeNull();
  }, SLOW);

  it('rejects a different escrow key cleanly', async () => {
    const other = (await crypto.subtle.generateKey(
      { name: 'RSA-OAEP', modulusLength: 2048, publicExponent: new Uint8Array([1, 0, 1]), hash: 'SHA-256' },
      true,
      ['encrypt', 'decrypt'],
    )) as CryptoKeyPair;
    expect(await unlockWithEscrowKey(marker, other.privateKey)).toBeNull();
  }, SLOW);

  it('still opens with the password and with the user recovery key', async () => {
    expect(await unlockWithPassword(marker, PW)).not.toBeNull();
    expect(await unlockWithRecoveryKey(marker, recoveryKey)).not.toBeNull();
  }, SLOW);
});

// ─────────────────────────────────────────────────────────────────────
// 4b. Which escrow door applies to THIS folder
// ─────────────────────────────────────────────────────────────────────
//
// Escrow can now be ADOPTED by an installation that already has folders,
// and adoption is not retroactive: a folder created before it carries no
// escrow slot and never will. The UI has to be able to tell the operator
// that, in words — "no Escrow tab" on its own reads as a bug to an admin
// who knows escrow is enabled here, so they try the key and learn the
// truth from a failure.
//
// escrowAvailability is the single place that decision is made. Its
// 'other-key' branch also closes an older, quieter lie: the dialog used to
// label the escrow field with the INSTALLATION's key id whatever the
// folder's own slot said, so a folder restored from another install looked
// openable with a key that cannot open it.

describe('escrowAvailability', () => {
  let withEscrow: E2eMarker;
  let withoutEscrow: E2eMarker;
  let ourKid: string;

  beforeAll(async () => {
    ourKid = await escrowKeyId(escrowTestKey.public_spki_b64);
    withEscrow = wire(
      (await createEncryptedFolder(PW, { escrowPublicKey: escrowTestKey.public_spki_b64 })).marker,
    );
    withoutEscrow = wire((await createEncryptedFolder(PW, {})).marker);
  }, SLOW);

  it('says "off" when the installation has no escrow key at all', () => {
    expect(escrowAvailability(withoutEscrow, null)).toBe('off');
    expect(escrowAvailability(withEscrow, null)).toBe('off');
    expect(escrowAvailability(withEscrow, '')).toBe('off');
  });

  it('says "available" only when the folder is sealed to THIS key', () => {
    expect(escrowAvailability(withEscrow, ourKid)).toBe('available');
  });

  it('says "predates" for a folder made before escrow was adopted', () => {
    // The whole point. The installation has a key; this folder does not.
    expect(escrowAvailability(withoutEscrow, ourKid)).toBe('predates');
  });

  it('says "other-key" for a folder restored from another installation', () => {
    const foreign = wire({ ...withEscrow, esc: { ...withEscrow.esc!, kid: 'ffffffffffffffff' } });
    expect(escrowAvailability(foreign, ourKid)).toBe('other-key');
  });

  it('treats a v1 marker as predating escrow, not as escrowed', async () => {
    const v1 = wire((await createMarker(PW)).marker);
    expect(escrowAvailability(v1, ourKid)).toBe('predates');
  }, SLOW);

  it('never claims a door for a missing marker', () => {
    expect(escrowAvailability(null, ourKid)).toBe('predates');
    expect(escrowAvailability(null, null)).toBe('off');
  });
});

// ─────────────────────────────────────────────────────────────────────
// 4c. Offering an existing folder an escrow slot
// ─────────────────────────────────────────────────────────────────────
//
// Adoption covers folders created after it and nothing else, which on a
// real installation means it covers nothing anybody cares about — the
// folders that matter already exist. The server still cannot reach them:
// adding a slot needs the folder master key. The OWNER can, from inside,
// with the password, at the moment of an unlock.
//
// These tests hold the two edges of that. Accepting really does hand the
// escrow key a working door (measured to plaintext, not to a truthy
// object). Declining really does close it and keep it closed.

describe('offering an existing folder an escrow slot', () => {
  const secret = 'ledger.xlsx';
  let ourKid: string;
  let priv: CryptoKey;

  beforeAll(async () => {
    ourKid = await escrowKeyId(escrowTestKey.public_spki_b64);
    priv = await importEscrowPrivateKey(escrowTestKey.private_pkcs8_b64);
  }, SLOW);

  /** A v2 folder created while escrow was off, plus one encrypted file. */
  async function folderWithoutEscrow() {
    const made = await createEncryptedFolder(PW, {});
    return {
      marker: wire(made.marker),
      file: await encryptFile(made.fmk, enc.encode(secret).buffer as ArrayBuffer),
      recoveryKey: made.recoveryKey,
    };
  }

  it('is offered exactly when it can be honoured', async () => {
    const { marker } = await folderWithoutEscrow();
    // The installation has no key: there is nothing to offer.
    expect(escrowOfferState(marker, null)).toBe('n/a');
    expect(escrowOfferState(marker, '')).toBe('n/a');
    // It has one, and this folder has no slot.
    expect(escrowOfferState(marker, ourKid)).toBe('offer');
    // A folder that already has a slot is not asked again.
    const sealed = wire(
      (await createEncryptedFolder(PW, { escrowPublicKey: escrowTestKey.public_spki_b64 })).marker,
    );
    expect(escrowOfferState(sealed, ourKid)).toBe('n/a');
    // A v1 marker belongs to upgradeMarkerV1, which discloses escrow itself.
    // Two doors into the same room would be two chances to get it wrong.
    const v1 = wire((await createMarker(PW)).marker);
    expect(escrowOfferState(v1, ourKid)).toBe('n/a');
    expect(escrowOfferState(null, ourKid)).toBe('n/a');
  }, SLOW);

  it('accepting gives the escrow key a door, all the way to plaintext', async () => {
    const { marker, file } = await folderWithoutEscrow();
    expect(await unlockWithEscrowKey(marker, priv)).toBeNull();

    const next = wire(await addEscrowSlot(marker, PW, escrowTestKey.public_spki_b64));
    expect(markerHasEscrow(next)).toBe(true);
    expect(next.esc!.kid).toBe(ourKid);
    expect(next.esc!.alg).toBe('RSA-OAEP-256');

    const fmk = await unlockWithEscrowKey(next, priv);
    expect(fmk).not.toBeNull();
    // The file was encrypted BEFORE the slot existed and is not rewritten.
    expect(dec.decode(await decryptFile(fmk!, file))).toBe(secret);
  }, SLOW);

  it('leaves the password and the recovery key working, and the files untouched', async () => {
    const { marker, file, recoveryKey } = await folderWithoutEscrow();
    const next = wire(await addEscrowSlot(marker, PW, escrowTestKey.public_spki_b64));

    // Same salt, same iterations, same verify blob, same wrapped FMK: the
    // only difference is the new slot.
    expect(next.salt).toBe(marker.salt);
    expect(next.iter).toBe(marker.iter);
    expect(next.verify).toBe(marker.verify);
    expect(next.fmk_pw).toBe(marker.fmk_pw);
    expect(next.rk).toEqual(marker.rk);

    const byPw = await unlockWithPassword(next, PW);
    expect(byPw).not.toBeNull();
    expect(dec.decode(await decryptFile(byPw!, file))).toBe(secret);
    expect(await unlockWithRecoveryKey(next, recoveryKey)).not.toBeNull();
  }, SLOW);

  it('refuses a wrong password instead of writing a slot nobody can use', async () => {
    const { marker } = await folderWithoutEscrow();
    await expect(
      addEscrowSlot(marker, PW + 'x', escrowTestKey.public_spki_b64),
    ).rejects.toThrow();
  }, SLOW);

  it('refuses to add a second slot, or to touch a v1 marker', async () => {
    const sealed = wire(
      (await createEncryptedFolder(PW, { escrowPublicKey: escrowTestKey.public_spki_b64 })).marker,
    );
    await expect(addEscrowSlot(sealed, PW, escrowTestKey.public_spki_b64)).rejects.toThrow();
    const v1 = wire((await createMarker(PW)).marker);
    await expect(addEscrowSlot(v1, PW, escrowTestKey.public_spki_b64)).rejects.toThrow();
  }, SLOW);

  it('works on a v1 folder that was upgraded in place (fmk: kek)', async () => {
    // The awkward mode: the FMK *is* the password key, so the slot has to
    // wrap those very bytes. Upgraded with escrow OFF, so there is no slot
    // to inherit.
    const v1 = wire((await createMarker(PW)).marker);
    const up = await upgradeMarkerV1(v1, PW, {});
    const upgraded = wire(up.marker);
    expect(upgraded.fmk).toBe('kek');
    expect(markerHasEscrow(upgraded)).toBe(false);
    const file = await encryptFile(up.fmk, enc.encode(secret).buffer as ArrayBuffer);

    const next = wire(await addEscrowSlot(upgraded, PW, escrowTestKey.public_spki_b64));
    const fmk = await unlockWithEscrowKey(next, priv);
    expect(fmk).not.toBeNull();
    expect(dec.decode(await decryptFile(fmk!, file))).toBe(secret);
  }, SLOW);

  it('a decline is a decision: recorded, not re-asked, and reversible', async () => {
    const { marker } = await folderWithoutEscrow();
    const declined = wire(declineEscrowSlot(marker, '2026-09-05T12:00:00Z'));
    expect(declined.esc_declined).toBe('2026-09-05T12:00:00Z');
    expect(escrowOfferState(declined, ourKid)).toBe('declined');
    // Declining changes no key material whatsoever.
    expect(markerHasEscrow(declined)).toBe(false);
    expect(declined.fmk_pw).toBe(marker.fmk_pw);
    expect(declined.rk).toEqual(marker.rk);
    expect(await unlockWithPassword(declined, PW)).not.toBeNull();

    // ...and the way back exists, without deleting and re-creating anything.
    const later = wire(await addEscrowSlot(declined, PW, escrowTestKey.public_spki_b64));
    expect(later.esc_declined).toBeUndefined();
    expect(escrowOfferState(later, ourKid)).toBe('n/a');
    expect(await unlockWithEscrowKey(later, priv)).not.toBeNull();
  }, SLOW);

  it('the escrow key still does not open a declined folder', async () => {
    const { marker, file } = await folderWithoutEscrow();
    const declined = wire(declineEscrowSlot(marker, '2026-09-05T12:00:00Z'));
    expect(await unlockWithEscrowKey(declined, priv)).toBeNull();
    // And not by borrowing another folder's key either — the FMK the escrow
    // key CAN produce on this installation is a different folder's.
    const other = wire(
      (await createEncryptedFolder(PW, { escrowPublicKey: escrowTestKey.public_spki_b64 })).marker,
    );
    const otherFmk = await unlockWithEscrowKey(other, priv);
    expect(otherFmk).not.toBeNull();
    await expect(decryptFile(otherFmk!, file)).rejects.toThrow();
  }, SLOW);

  it('survives the wire: esc_declined is a real marker field, not memory', async () => {
    const { marker } = await folderWithoutEscrow();
    const declined = declineEscrowSlot(marker, '2026-09-05T12:00:00Z');
    const roundTripped = parseMarker(JSON.stringify(declined));
    expect(roundTripped).not.toBeNull();
    expect(escrowOfferState(roundTripped, ourKid)).toBe('declined');
  }, SLOW);
});

// ─────────────────────────────────────────────────────────────────────
// 5. Giving an existing v1 folder recovery, in place
// ─────────────────────────────────────────────────────────────────────

describe('upgrading a v1 folder in place', () => {
  const oldSecret = 'written in 2026 under v1';
  let v1Marker: E2eMarker;
  let v1File: ArrayBuffer;

  beforeAll(async () => {
    const made = await legacy.createMarker(PW);
    v1Marker = wire(made.marker as E2eMarker);
    v1File = await legacy.encryptFile(made.kek, enc.encode(oldSecret).buffer as ArrayBuffer);
  }, SLOW);

  it('keeps the password opening the files that already exist', async () => {
    const up = await upgradeMarkerV1(v1Marker, PW);
    const m = wire(up.marker);
    expect(m.fmk).toBe('kek'); // the files were not rewritten, so neither was the key
    expect(m.salt).toBe(v1Marker.salt); // and the password derivation is untouched
    const fmk = await unlockWithPassword(m, PW);
    expect(dec.decode(await decryptFile(fmk!, v1File))).toBe(oldSecret);
  }, SLOW);

  it('lets the new recovery key open those same pre-existing files', async () => {
    const up = await upgradeMarkerV1(v1Marker, PW);
    const m = wire(up.marker);
    const fmk = await unlockWithRecoveryKey(m, up.recoveryKey);
    expect(fmk).not.toBeNull();
    expect(dec.decode(await decryptFile(fmk!, v1File))).toBe(oldSecret);
  }, SLOW);

  it('leaves the folder readable by the OLD module — an upgrade is not a one-way door', async () => {
    const up = await upgradeMarkerV1(v1Marker, PW);
    // The old build cannot parse a v2 marker, but the FILES are unchanged and
    // the key the old code derives from the password still opens them. A
    // rolled-back deployment loses the recovery UI, not the data.
    const legacyKek = await legacy.verifyPassword(v1Marker as never, PW);
    expect(dec.decode(await legacy.decryptFile(legacyKek!, v1File))).toBe(oldSecret);
    expect(up.marker.v).toBe(2);
  }, SLOW);

  it('adds escrow when the installation has it on', async () => {
    const up = await upgradeMarkerV1(v1Marker, PW, {
      escrowPublicKey: escrowTestKey.public_spki_b64,
    });
    const m = wire(up.marker);
    const priv = await importEscrowPrivateKey(escrowTestKey.private_pkcs8_b64);
    const fmk = await unlockWithEscrowKey(m, priv);
    expect(fmk).not.toBeNull();
    // ⚠ This is the one way a folder gains escrow after the fact, and it is
    // why the UI must say so before asking: it needs the password, so only
    // the user can do it, but they must know what they are agreeing to.
    expect(dec.decode(await decryptFile(fmk!, v1File))).toBe(oldSecret);
  }, SLOW);

  it('refuses a wrong password instead of writing a marker nobody can open', async () => {
    await expect(upgradeMarkerV1(v1Marker, 'wrong password')).rejects.toThrow();
  }, SLOW);

  it('refuses to run twice — a v2 marker is not a v1 marker', async () => {
    const up = await upgradeMarkerV1(v1Marker, PW);
    await expect(upgradeMarkerV1(up.marker, PW)).rejects.toThrow(/not a v1 marker/);
  }, SLOW);

  it('gives every upgrade a different recovery key', async () => {
    const a = await upgradeMarkerV1(v1Marker, PW);
    const b = await upgradeMarkerV1(v1Marker, PW);
    expect(a.recoveryKey).not.toBe(b.recoveryKey);
    // Both are valid — the second supersedes nothing, because the marker the
    // caller keeps is whichever one it uploads.
    expect(await unlockWithRecoveryKey(wire(a.marker), a.recoveryKey)).not.toBeNull();
    expect(await unlockWithRecoveryKey(wire(b.marker), b.recoveryKey)).not.toBeNull();
    expect(await unlockWithRecoveryKey(wire(a.marker), b.recoveryKey)).toBeNull();
  }, SLOW);
});

// ─────────────────────────────────────────────────────────────────────
// 6. Marker parsing — what a corrupt or hostile marker may do
// ─────────────────────────────────────────────────────────────────────

describe('parseMarker', () => {
  it('rejects an unknown version rather than guessing', () => {
    expect(parseMarker('{"v":3,"salt":"AA==","iter":600000,"verify":"AA=="}')).toBeNull();
  });

  it('rejects a v2 marker with no fmk mode', () => {
    expect(parseMarker('{"v":2,"salt":"AA==","iter":600000,"verify":"AA=="}')).toBeNull();
  });

  it('rejects a wrapped-mode marker with no wrapped key', () => {
    expect(
      parseMarker('{"v":2,"fmk":"wrapped","salt":"AA==","iter":600000,"verify":"AA=="}'),
    ).toBeNull();
  });

  it('rejects junk', () => {
    expect(parseMarker('')).toBeNull();
    expect(parseMarker('not json')).toBeNull();
    expect(parseMarker('null')).toBeNull();
  });
});
