#!/usr/bin/env node
/**
 * dup-scan — find the same logic written twice.
 *
 * WHY THIS EXISTS
 * ---------------
 * "Tekrar eden şeyler tek yerden eklenmeli, tek yerden yönetilmeli." Every
 * time that rule was broken in this repo it was caught by a person looking at
 * a screen, never by a check: a 464-line second listing pane, the same
 * `mime_type === 'inode/storage'` line in three view components, a brand mark
 * hand-built as an inline SVG in two more files after the component was
 * recoloured, two date formatters that disagreed. The second copy always gets
 * written because the first is inconvenient to reach, nothing notices, and the
 * two drift.
 *
 * WHAT IT LOOKS FOR
 * -----------------
 * Two passes over the same normalised token stream, because the real cases
 * come in two shapes and one threshold cannot serve both:
 *
 *   verbatim  identifiers kept as written. This is copy-paste: the block was
 *             moved with the mouse and the names came along. Cheap to be sure
 *             about, so the token floor can be low.
 *
 *   renamed   identifiers, strings and numbers collapsed to placeholders. This
 *             is the block that was re-typed, or copied and then adapted, so
 *             `parts`/`segs` and `part`/`s` no longer match. A line-hash or a
 *             value-token detector misses exactly this, and it is most of the
 *             list above — so it gets a higher token floor plus a much
 *             stricter shape filter (see DEFAULTS) to keep boilerplate out.
 *
 * Both passes report *maximal* clone groups: three copies of one fragment come
 * back as one finding with three sites, not three findings.
 *
 * WHAT IT DOES NOT LOOK FOR
 * -------------------------
 * - Vue `<template>` and `<style>` blocks. Logic only; repeated markup and
 *   repeated CSS are a different argument with a different answer.
 * - Behaviour. Two date formatters that disagree while sharing no tokens are
 *   invisible here — that one needs a test, not a scanner.
 * - Tests. `*_test.go` / `*.test.ts` are excluded: table-driven tests are
 *   repetitive on purpose and would drown the signal on day one.
 *
 * USE
 * ---
 *   node scripts/dup-scan.mjs                 human-readable ranked report
 *   node scripts/dup-scan.mjs --json          machine output (the gate uses this)
 *   node scripts/dup-scan.mjs --min-verbatim 60 --min-renamed 120
 *   node scripts/dup-scan.mjs --only packages/core/src
 *   node scripts/dup-scan.mjs --root <dir> --only src     (used by the gate's
 *                                                          own fixture tests)
 *
 * The gate that consumes it: web/tests/quality/duplication.test.ts
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = path.resolve(HERE, '..');

// ---------------------------------------------------------------------------
// Scope
// ---------------------------------------------------------------------------

/** Directories that hold code we wrote and maintain. */
export const SCAN_ROOTS = [
  'packages/core/src',
  'web/src',
  'backend/internal',
  'desktop/src',
];

/**
 * Paths that are not "the same logic written twice", with the reason.
 *
 * ⚠ This is a SCOPE list, not an escape hatch — it says "this file is not
 * hand-written logic". A real duplicate you do not want to fix goes in the
 * gate's LEGITIMATE_TWINS / KNOWN_DUPLICATION lists, where it is visible.
 */
export const SCOPE_EXCLUSIONS = [
  {
    match: (rel) => /(^|\/)locales\//.test(rel),
    why: 'en.ts and tr.ts are two catalogues of the same keys by design; that is the feature, not a clone',
  },
  {
    match: (rel) => /\.d\.ts$/.test(rel),
    why: 'generated type declarations',
  },
  {
    match: (rel) => /_test\.go$|\.test\.ts$|\.spec\.ts$/.test(rel),
    why: 'table-driven tests repeat on purpose',
  },
  {
    match: (rel) => /(^|\/)(testdata|node_modules|dist|embed)\//.test(rel),
    why: 'fixtures, build output, vendored trees',
  },
];

const CODE_EXT = new Set(['.ts', '.tsx', '.cts', '.mts', '.vue', '.go']);

/** First lines that mark a file as produced by a tool rather than a person. */
const GENERATED_RE = /Code generated by|@generated|DO NOT EDIT/i;

// ---------------------------------------------------------------------------
// Thresholds — see the header of the gate test for how these were chosen.
// ---------------------------------------------------------------------------

export const DEFAULTS = {
  /** Contiguous tokens, identifiers intact, before a copy-paste is a finding. */
  minVerbatim: 100,
  /** Contiguous tokens, identifiers blanked, before a re-typed block is a finding. */
  minRenamed: 140,
  /**
   * How many DISTINCT structural tokens a clone must carry — keywords and
   * operators; the ubiquitous `( ) , ; . { } [ ] :` and every name do not
   * count. It is the difference between duplicated LOGIC and a repeated data
   * table, and the two passes need very different floors:
   *
   * verbatim: low. Identical tokens INCLUDING the names is already strong
   *   evidence; the filter is only here to drop declarative tables — a theme
   *   map, a route list, a shortcut catalogue — where `$STR : $STR ,` repeats
   *   and the structural score is 0-2. Measured: at 14 this pass threw away a
   *   byte-for-byte identical 194-token block shared by ftpsrv/fileinfo.go and
   *   sftpsrv/fileinfo.go (score 10), which is exactly the kind of hit the
   *   gate exists for.
   *
   * renamed: high. Every name is `$ID` here, so the shape is ALL the evidence
   *   there is. Below ~12 the pass reports 110 tokens of `$ID.$ID($ID, $ID);`
   *   as a clone and the gate is noise inside a week.
   */
  minShapeVerbatim: 6,
  minShapeRenamed: 14,
  /**
   * Ignore a k-gram that occurs more often than this. A shape that appears 60
   * times is a language idiom, not a copied block, and pairing them up is
   * quadratic.
   */
  maxOccurrences: 24,
};

// ---------------------------------------------------------------------------
// Lexers
// ---------------------------------------------------------------------------

/**
 * Reserved words are STRUCTURE, not names.
 *
 * They stay themselves in the renamed pass, which is what makes the shape
 * filter mean anything: with keywords blanked to `$ID` alongside every
 * variable, a 110-token block carries almost no distinct structural tokens and
 * the filter either passes everything or nothing. (Measured: with keywords
 * blanked, `minDistinctShape: 12` found 3 clones in the whole tree at every
 * token floor from 40 to 110 — the filter was answering a question about
 * punctuation.)
 */
const JS_RESERVED = new Set([
  'abstract', 'as', 'async', 'await', 'break', 'case', 'catch', 'class', 'const',
  'continue', 'declare', 'default', 'delete', 'do', 'else', 'enum', 'export',
  'extends', 'false', 'finally', 'for', 'from', 'function', 'get', 'if',
  'implements', 'import', 'in', 'infer', 'instanceof', 'interface', 'is',
  'keyof', 'let', 'namespace', 'new', 'null', 'of', 'private', 'protected',
  'public', 'readonly', 'return', 'satisfies', 'set', 'static', 'super',
  'switch', 'this', 'throw', 'true', 'try', 'type', 'typeof', 'undefined',
  'var', 'void', 'while', 'yield',
]);

const GO_RESERVED = new Set([
  'append', 'bool', 'break', 'byte', 'cap', 'case', 'chan', 'close', 'complex',
  'const', 'continue', 'copy', 'default', 'defer', 'delete', 'else', 'error',
  'fallthrough', 'false', 'float32', 'float64', 'for', 'func', 'go', 'goto',
  'if', 'import', 'int', 'int32', 'int64', 'interface', 'iota', 'len', 'make',
  'map', 'new', 'nil', 'package', 'panic', 'range', 'recover', 'return',
  'rune', 'select', 'string', 'struct', 'switch', 'true', 'type', 'uint',
  'uint32', 'uint64', 'var',
]);

/** Reserved words that END an expression, so a following `/` is division. */
const JS_VALUE_KEYWORDS = new Set(['this', 'super', 'true', 'false', 'null', 'undefined']);

const JS_PUNCT = [
  '>>>=', '...', '===', '!==', '**=', '<<=', '>>=', '>>>', '&&=', '||=', '??=',
  '=>', '==', '!=', '<=', '>=', '&&', '||', '??', '?.', '++', '--', '+=', '-=',
  '*=', '/=', '%=', '&=', '|=', '^=', '**', '<<', '>>',
  '{', '}', '(', ')', '[', ']', ';', ',', '<', '>', '+', '-', '*', '/', '%',
  '&', '|', '^', '!', '~', '?', ':', '=', '.', '@', '#',
];

const GO_PUNCT = [
  '<<=', '>>=', '&^=', '...', '&^', ':=', '<-', '++', '--', '==', '!=', '<=',
  '>=', '&&', '||', '+=', '-=', '*=', '/=', '%=', '&=', '|=', '^=', '<<', '>>',
  '{', '}', '(', ')', '[', ']', ';', ',', '<', '>', '+', '-', '*', '/', '%',
  '&', '|', '^', '!', '~', '?', ':', '=', '.',
];

const IDENT_START = /[A-Za-z_$]/;
const IDENT_PART = /[A-Za-z0-9_$]/;

/**
 * Turn source into `{ v, t, line }` tokens. Comments and whitespace vanish.
 *
 * `t` is one of: id | num | str | punct. The caller decides what to do with
 * the value; both passes share this stream so a file is lexed once.
 */
export function tokenize(src, lang, opts = {}) {
  const commentRanges = opts.commentRanges;
  const punct = lang === 'go' ? GO_PUNCT : JS_PUNCT;
  const reserved = lang === 'go' ? GO_RESERVED : JS_RESERVED;
  const out = [];
  let i = 0;
  let line = 1;
  const n = src.length;
  /**
   * Explicit mode stack for template literals. `code` counts open braces so we
   * know which `}` ends an interpolation; `tpl` means we are inside the string
   * part. Nesting works because a nested backtick just pushes another `tpl`.
   */
  const modes = [{ kind: 'code', depth: 0 }];
  const mode = () => modes[modes.length - 1];

  const push = (v, t) => out.push({ v, t, line });
  const prev = () => (out.length ? out[out.length - 1] : null);

  const countNewlines = (from, to) => {
    for (let k = from; k < to; k++) if (src.charCodeAt(k) === 10) line++;
  };

  while (i < n) {
    const c = src[i];

    // Inside the literal text of a template: consume until the literal ends
    // or an interpolation opens. One `$STR` stands for the whole chunk.
    if (mode().kind === 'tpl') {
      let j = i;
      let emitted = false;
      while (j < n) {
        if (src[j] === '\\') { j += 2; continue; }
        if (src[j] === '`') { modes.pop(); j++; break; }
        if (src[j] === '$' && src[j + 1] === '{') break;
        if (src[j] === '\n') line++;
        j++;
        emitted = true;
      }
      if (emitted) push('$STR', 'str');
      if (j < n && src[j] === '$' && src[j + 1] === '{') {
        push('${', 'punct');
        modes.push({ kind: 'code', depth: 0 });
        j += 2;
      }
      i = j > i ? j : i + 1;
      continue;
    }

    if (c === '\n') { line++; i++; continue; }
    if (c === ' ' || c === '\t' || c === '\r') { i++; continue; }

    // comments
    if (c === '/' && src[i + 1] === '/') {
      const nl = src.indexOf('\n', i);
      const stop = nl < 0 ? n : nl;
      if (commentRanges) commentRanges.push([i, stop]);
      i = stop;
      continue;
    }
    if (c === '/' && src[i + 1] === '*') {
      const end = src.indexOf('*/', i + 2);
      const stop = end < 0 ? n : end + 2;
      if (commentRanges) commentRanges.push([i, stop]);
      countNewlines(i, stop);
      i = stop;
      continue;
    }

    // strings
    if (c === '"' || c === "'" || (lang === 'go' && c === '`')) {
      const quote = c;
      let j = i + 1;
      while (j < n) {
        if (src[j] === '\\' && quote !== '`') { j += 2; continue; }
        if (src[j] === quote) { j++; break; }
        if (src[j] === '\n' && quote !== '`') { j++; break; }
        j++;
      }
      push('$STR', 'str');
      countNewlines(i, j);
      i = j;
      continue;
    }

    // JS template literal — the literal chunks become $STR, the `${}`
    // expressions are tokenized normally so logic inside them still counts.
    if (lang !== 'go' && c === '`') {
      modes.push({ kind: 'tpl' });
      i++;
      continue;
    }

    // Braces, tracked so the `}` that closes an interpolation pops back into
    // the literal instead of being read as the end of a block.
    if (lang !== 'go' && (c === '{' || c === '}')) {
      const m = mode();
      if (c === '{') {
        m.depth++;
        push('{', 'punct');
      } else if (m.depth === 0 && modes.length > 1) {
        modes.pop(); // back into the surrounding `tpl`
        push('}$', 'punct');
      } else {
        m.depth--;
        push('}', 'punct');
      }
      i++;
      continue;
    }

    // regex literal (JS only) — a `/` here is a regex when the previous
    // significant token cannot end an expression.
    if (lang !== 'go' && c === '/') {
      const p = prev();
      let regexOk = true;
      if (p) {
        if (p.t === 'num' || p.t === 'str' || p.t === 'id') regexOk = false;
        else if (p.t === 'kw') regexOk = !JS_VALUE_KEYWORDS.has(p.v);
        else if (p.v === ')' || p.v === ']' || p.v === '++' || p.v === '--') regexOk = false;
      }
      if (regexOk) {
        let j = i + 1;
        let klass = false;
        let ok = false;
        while (j < n) {
          const d = src[j];
          if (d === '\\') { j += 2; continue; }
          if (d === '\n') break;
          if (d === '[') klass = true;
          else if (d === ']') klass = false;
          else if (d === '/' && !klass) { j++; ok = true; break; }
          j++;
        }
        if (ok) {
          while (j < n && /[a-z]/.test(src[j])) j++;
          push('$RE', 'str');
          i = j;
          continue;
        }
      }
    }

    // numbers
    if (/[0-9]/.test(c) || (c === '.' && /[0-9]/.test(src[i + 1] || ''))) {
      let j = i;
      while (j < n && /[0-9a-fA-FxXoObBeEnN_.+-]/.test(src[j])) {
        // stop a `+`/`-` that is not an exponent sign
        if ((src[j] === '+' || src[j] === '-') && !/[eE]/.test(src[j - 1])) break;
        if (src[j] === '.' && src[j + 1] === '.') break;
        j++;
      }
      push('$NUM', 'num');
      i = j;
      continue;
    }

    // identifiers and reserved words
    if (IDENT_START.test(c)) {
      let j = i + 1;
      while (j < n && IDENT_PART.test(src[j])) j++;
      const word = src.slice(i, j);
      push(word, reserved.has(word) ? 'kw' : 'id');
      i = j;
      continue;
    }

    // punctuation
    let matched = null;
    for (const p of punct) {
      if (src.startsWith(p, i)) { matched = p; break; }
    }
    if (matched) {
      push(matched, 'punct');
      i += matched.length;
      continue;
    }

    i++; // unknown byte
  }

  return out;
}

/** `<script>` blocks of a Vue SFC, with the line they start on. */
export function extractVueScripts(src) {
  const out = [];
  const re = /<script\b[^>]*>/gi;
  let m;
  while ((m = re.exec(src))) {
    const start = m.index + m[0].length;
    const end = src.indexOf('</script>', start);
    if (end < 0) break;
    let lineOffset = 0;
    for (let k = 0; k < start; k++) if (src.charCodeAt(k) === 10) lineOffset++;
    out.push({ code: src.slice(start, end), lineOffset });
    re.lastIndex = end + 9;
  }
  return out;
}

// ---------------------------------------------------------------------------
// File collection
// ---------------------------------------------------------------------------

function walk(dir, acc, exts = CODE_EXT) {
  const want = exts instanceof Set ? exts : new Set(exts);
  let entries;
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return acc;
  }
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) {
      if (e.name === 'node_modules' || e.name === 'dist' || e.name === '.git') continue;
      walk(full, acc, want);
    } else if (e.isFile() && want.has(path.extname(e.name))) {
      acc.push(full);
    }
  }
  return acc;
}

/**
 * One read per file per process. The three mechanisms walk overlapping trees
 * (the brand mark lives in Go, HTML and Vue), and re-reading `backend/internal`
 * four times was most of the runtime.
 */
const readCache = new Map();
function readFile(abs) {
  let hit = readCache.get(abs);
  if (hit === undefined) {
    try { hit = fs.readFileSync(abs, 'utf8'); } catch { hit = null; }
    readCache.set(abs, hit);
  }
  return hit;
}

export function collectFiles(roots = SCAN_ROOTS, repoRoot = REPO_ROOT) {
  const files = [];
  for (const root of roots) {
    walk(path.join(repoRoot, root), files);
  }
  const kept = [];
  for (const abs of files) {
    const rel = path.relative(repoRoot, abs).split(path.sep).join('/');
    if (SCOPE_EXCLUSIONS.some((x) => x.match(rel))) continue;
    const src = readFile(abs);
    if (src === null || GENERATED_RE.test(src.slice(0, 400))) continue;
    kept.push({ rel, src });
  }
  kept.sort((a, b) => (a.rel < b.rel ? -1 : a.rel > b.rel ? 1 : 0));
  return kept;
}

// ---------------------------------------------------------------------------
// Token stream
// ---------------------------------------------------------------------------

/**
 * One flat token stream for the whole corpus, plus the file/line each token
 * came from. A sentinel between files means no window can straddle two files.
 */
export function buildStream(files) {
  /** @type {{rel:string}[]} */
  const units = [];
  const v = [];      // token value
  const t = [];      // token kind
  const unit = [];   // index into units
  const ln = [];     // line in the source file

  for (const f of files) {
    const ext = path.extname(f.rel);
    if (ext === '.vue') {
      const blocks = extractVueScripts(f.src);
      for (const b of blocks) {
        const idx = units.length;
        units.push({ rel: f.rel });
        for (const tok of tokenize(b.code, 'js')) {
          v.push(tok.v); t.push(tok.t); unit.push(idx); ln.push(b.lineOffset + tok.line);
        }
      }
    } else {
      const idx = units.length;
      units.push({ rel: f.rel });
      const lang = ext === '.go' ? 'go' : 'js';
      for (const tok of tokenize(f.src, lang)) {
        v.push(tok.v); t.push(tok.t); unit.push(idx); ln.push(tok.line);
      }
    }
  }
  return { units, v, t, unit, ln };
}

/** Values for the `renamed` pass: names, strings and numbers become shapes. */
function renamedValues(stream) {
  const out = new Array(stream.v.length);
  for (let i = 0; i < out.length; i++) {
    const kind = stream.t[i];
    // Reserved words (`kind === 'kw'`) survive: they are the shape of the code.
    out[i] = kind === 'id' ? '$ID' : kind === 'num' ? '$NUM' : kind === 'str' ? '$STR' : stream.v[i];
  }
  return out;
}

// ---------------------------------------------------------------------------
// Clone detection
// ---------------------------------------------------------------------------

const NOISE_PUNCT = new Set(['(', ')', ',', ';', '.', '{', '}', '[', ']', ':']);

/** Distinct keyword/operator tokens in a slice — how much *shape* it carries. */
function distinctShape(values, kinds, from, len) {
  const seen = new Set();
  for (let i = from; i < from + len; i++) {
    const k = kinds[i];
    if (k === 'num' || k === 'str') continue;
    const val = values[i];
    if (k === 'punct' && NOISE_PUNCT.has(val)) continue;
    if (val === '$ID') continue;
    seen.add(val);
  }
  return seen.size;
}

function intern(values) {
  const map = new Map();
  const ids = new Int32Array(values.length);
  for (let i = 0; i < values.length; i++) {
    let id = map.get(values[i]);
    if (id === undefined) { id = map.size + 1; map.set(values[i], id); }
    ids[i] = id;
  }
  return ids;
}

/**
 * Maximal duplicated token runs of at least `k` tokens.
 *
 * Greedy left to right with a covered-bitmap, so a run is reported once as a
 * group of sites rather than once per shifted window, and the work stays
 * roughly linear in the corpus.
 */
function findClones({ values, shapeValues, kinds, stream, k, maxOcc, minShape }) {
  const n = values.length;
  if (n < k) return [];
  const ids = intern(values);
  const MOD = 0x100000000;
  const BASE = 1000003;

  let power = 1;
  for (let i = 0; i < k - 1; i++) power = Math.imul(power, BASE) >>> 0;

  const hashes = new Int32Array(n - k + 1);
  const spanOk = new Uint8Array(n - k + 1);
  let h = 0;
  for (let i = 0; i < k; i++) h = (Math.imul(h, BASE) + ids[i]) >>> 0;
  hashes[0] = h | 0;
  spanOk[0] = stream.unit[0] === stream.unit[k - 1] ? 1 : 0;
  for (let i = 1; i <= n - k; i++) {
    h = (h - Math.imul(ids[i - 1], power)) >>> 0;
    h = (Math.imul(h, BASE) + ids[i + k - 1]) >>> 0;
    hashes[i] = h | 0;
    spanOk[i] = stream.unit[i] === stream.unit[i + k - 1] ? 1 : 0;
  }

  /** @type {Map<number, number[]>} */
  const index = new Map();
  for (let i = 0; i <= n - k; i++) {
    if (!spanOk[i]) continue;
    const key = hashes[i];
    const bucket = index.get(key);
    if (bucket === undefined) index.set(key, [i]);
    else if (bucket.length <= maxOcc) bucket.push(i);
    else bucket.push(i); // keep counting so we can drop the whole bucket
  }

  const covered = new Uint8Array(n);
  const results = [];

  const sameRun = (a, b, len) => {
    const ua = stream.unit[a];
    const ub = stream.unit[b];
    for (let d = 0; d < len; d++) {
      if (stream.unit[a + d] !== ua || stream.unit[b + d] !== ub) return false;
      if (ids[a + d] !== ids[b + d]) return false;
    }
    return true;
  };

  for (let i = 0; i <= n - k; i++) {
    if (covered[i] || !spanOk[i]) continue;
    const bucket = index.get(hashes[i]);
    if (!bucket || bucket.length < 2 || bucket.length > maxOcc) continue;

    /** @type {{start:number,len:number}[]} */
    const partners = [];
    for (const j of bucket) {
      if (j <= i) continue;
      if (covered[j]) continue;
      if (j < i + k) continue; // overlapping windows in the same file
      if (!sameRun(i, j, k)) continue; // hash collision
      // extend right while the tokens agree and neither side leaves its file
      let len = k;
      const ua = stream.unit[i];
      const ub = stream.unit[j];
      while (
        i + len < n && j + len < n &&
        stream.unit[i + len] === ua && stream.unit[j + len] === ub &&
        ids[i + len] === ids[j + len] &&
        i + len < j
      ) len++;
      partners.push({ start: j, len });
    }
    if (partners.length === 0) continue;

    const len = Math.min(...partners.map((p) => p.len));
    // The shape score is ALWAYS read off the renamed projection, in both
    // passes. On the verbatim stream every distinct identifier would count,
    // so a theme map or a route table — many distinct keys, almost no
    // control flow — would score as the most structured code in the repo.
    if (minShape && distinctShape(shapeValues, kinds, i, len) < minShape) continue;

    const sites = [{ start: i, len }, ...partners.map((p) => ({ start: p.start, len }))];
    for (const s of sites) {
      for (let d = 0; d < s.len; d++) covered[s.start + d] = 1;
    }
    results.push({ tokens: len, sites });
  }

  return results;
}

function describeSite(stream, start, len) {
  const u = stream.unit[start];
  return {
    file: stream.units[u].rel,
    startLine: stream.ln[start],
    endLine: stream.ln[start + len - 1],
  };
}

// ---------------------------------------------------------------------------
// Second mechanism: one home per concept
// ---------------------------------------------------------------------------
//
// A token detector can only see a duplicate that is still SHAPED like the
// original. The worst cases in this repo are not: SecondaryPane re-implements
// the breadcrumb in 28 lines where Breadcrumb.vue takes 60, and the longest
// matching token run between the two files — with every identifier blanked —
// is 29 tokens. That is below any floor that would not also report every
// `if (!ok) return null` in the tree. (Measured both with this scanner and
// with jscpd 5.2's AST-similarity mode, which finds nothing between those two
// files at any setting from 0.85 down to 0.55.)
//
// So: a second, blunter mechanism. Some concepts have exactly one home here.
// Name the concept, name its home, name a `tell` that only that concept
// produces, and any OTHER file showing the tell is a second implementation. It
// catches the one-liner and the re-typed helper alike, because it does not
// care what the code looks like — only where it lives.

/** Strip comments, so a mention of a concept is not read as an instance of it. */
export function stripComments(src, ext) {
  let out = src;
  if (ext === '.html' || ext === '.svg' || ext === '.vue') {
    out = out.replace(/<!--[\s\S]*?-->/g, (m) => ' '.repeat(m.length));
  }
  if (ext === '.ts' || ext === '.tsx' || ext === '.cts' || ext === '.mts' || ext === '.go') {
    const ranges = [];
    tokenize(out, ext === '.go' ? 'go' : 'js', { commentRanges: ranges });
    out = blankRanges(out, ranges);
  }
  if (ext === '.vue') {
    // Only inside <script>: a `//` in the template is usually a URL.
    for (const b of extractVueScripts(out)) {
      const at = out.indexOf(b.code);
      if (at < 0) continue;
      const ranges = [];
      tokenize(b.code, 'js', { commentRanges: ranges });
      out = blankRanges(out, ranges.map(([a, z]) => [at + a, at + z]));
    }
  }
  return out;
}

function blankRanges(src, ranges) {
  if (!ranges.length) return src;
  const chars = [...src];
  for (const [a, z] of ranges) {
    for (let i = a; i < z && i < chars.length; i++) {
      if (chars[i] !== '\n') chars[i] = ' ';
    }
  }
  return chars.join('');
}

/**
 * Concepts with exactly one home.
 *
 * `tell` must be something ONLY that concept writes, and it must match inside
 * the home — the gate asserts that, so a concept that moves house fails loudly
 * instead of quietly passing everything.
 */
export const CONCEPTS = [
  {
    id: 'byte-size',
    what: 'turning a byte count into "1.4 GB"',
    /**
     * ONE home now. `web/src/lib/format.ts` used to be listed here too, and
     * that was the hole: two homes meant two bases (1000 there, 1024 in the
     * explorer) and nothing to say they disagreed. `formatBytes` delegates to
     * `formatByteSize` since 2026-09-13, so a hand-rolled formatter appearing
     * in format.ts again is a stray like any other.
     */
    home: ['packages/core/src/composables/useLocale.ts'],
    /**
     * Four alternatives, because a copy can be written four ways: a binary
     * ladder (1024), a decimal one (1000), a hardcoded unit table, or the
     * catalogue keys. The one implementation is generic over its base, so it
     * carries no ladder literal at all — `'unit.bytes'` is what identifies it,
     * and it is also what a translated copy would have to write.
     */
    tell: /\[\s*'B',\s*'KB'|\[\s*'K',\s*'M',\s*'G'|1024\s*\*\*|\/=\s*1024|>=\s*1024|1000\s*\*\*|\/=\s*1000|>=\s*1000|'unit\.bytes'/,
    roots: ['packages/core/src', 'web/src', 'desktop/src'],
    ext: ['.ts', '.vue'],
    fix: 'call formatByteSize() (or formatSize() from useLocale / formatBytes() from web/src/lib/format, which both do)',
  },
  {
    id: 'datetime-format',
    what: 'rendering an instant for a human',
    home: [
      'packages/core/src/composables/useLocale.ts',
      'packages/core/src/lib/timezone.ts',
      'web/src/lib/format.ts',
      'web/src/lib/timezone.ts',
    ],
    tell: /toLocaleDateString|toLocaleTimeString|toLocaleString\(|new Intl\.DateTimeFormat/,
    roots: ['packages/core/src', 'web/src', 'desktop/src'],
    ext: ['.ts', '.vue'],
    fix: "use formatDate()/formatDateFull() — they carry the viewer's locale AND chosen time zone",
  },
  {
    id: 'storage-row',
    what: 'recognising the synthetic "a storage" row in a listing',
    home: ['packages/core/src/lib/'],
    tell: /mime_type\s*===\s*'inode\/storage'/,
    roots: ['packages/core/src', 'web/src'],
    ext: ['.ts', '.vue'],
    fix: 'use the predicate from lib/fileIcons (or move it to lib/listing beside the other row helpers)',
  },
  {
    id: 'brand-mark',
    what: 'the filex logo',
    home: ['web/src/components/LogoMark.vue'],
    tell: /M7 11a2 2 0 0 1 2-2h5l2 2h7/,
    roots: ['packages/core/src', 'web/src', 'backend/internal', 'desktop/ui', 'site'],
    ext: ['.ts', '.vue', '.go', '.html', '.svg'],
    fix: 'generate the copy from LogoMark (the repo already syncs assets in scripts/sync-site-assets.mjs); do not re-type the path data',
  },
];

export function scanConcepts(repoRoot = REPO_ROOT) {
  const out = [];
  for (const concept of CONCEPTS) {
    const files = [];
    for (const root of concept.roots) walk(path.join(repoRoot, root), files, concept.ext);
    const homeHits = [];
    const strays = [];
    for (const abs of files) {
      const rel = path.relative(repoRoot, abs).split(path.sep).join('/');
      if (/(^|\/)(node_modules|dist|release|embed|build)\//.test(rel)) continue;
      if (SCOPE_EXCLUSIONS.some((x) => x.match(rel))) continue;
      const src = readFile(abs);
      if (src === null || !concept.tell.test(src)) continue;
      const clean = stripComments(src, path.extname(rel));
      const lines = [];
      clean.split('\n').forEach((l, i) => { if (concept.tell.test(l)) lines.push(i + 1); });
      if (!lines.length) continue;
      const atHome = concept.home.some((h) => (h.endsWith('/') ? rel.startsWith(h) : rel === h));
      (atHome ? homeHits : strays).push({ file: rel, lines });
    }
    strays.sort((a, b) => (a.file < b.file ? -1 : 1));
    out.push({ id: concept.id, what: concept.what, fix: concept.fix, home: concept.home, homeHits, strays });
  }
  return out;
}

// ---------------------------------------------------------------------------
// Third mechanism: a surface that reaches for SOME of the shared pieces
// ---------------------------------------------------------------------------
//
// What made SecondaryPane a second listing pane is not any line it contains.
// It is that it renders the three view components — so it IS a listing surface
// — while sourcing only two of the five shared pieces a listing surface is
// made of, and hand-rolling the rest. That is checkable from the import list,
// and it is exactly the defect: not "code that looks the same" but "a surface
// that decided to build its own".

export const COMPOSITION_RULES = [
  {
    id: 'listing-surface',
    what: 'a component that renders the shared view components is a listing surface',
    roots: ['packages/core/src', 'web/src'],
    /** Rendering this many of these makes a file a listing surface. */
    marker: ['ListView.vue', 'GridView.vue', 'GalleryView.vue'],
    markerMin: 2,
    /** …and a listing surface takes ALL of its chrome from these. */
    requires: [
      { import: 'Breadcrumb.vue', concept: 'the breadcrumb' },
      { import: 'FilterBar.vue', concept: 'the filter row' },
      { import: 'ViewSwitcher.vue', concept: 'the list/grid/gallery switch' },
      { import: 'lib/sortOrder', concept: 'the sort order' },
      { import: 'lib/listing', concept: 'the listing filter and the virtual rows' },
    ],
  },
];

export function scanComposition(repoRoot = REPO_ROOT) {
  const out = [];
  for (const rule of COMPOSITION_RULES) {
    const files = [];
    for (const root of rule.roots) walk(path.join(repoRoot, root), files, ['.vue']);
    const violations = [];
    const surfaces = [];
    for (const abs of files) {
      const rel = path.relative(repoRoot, abs).split(path.sep).join('/');
      const src = readFile(abs);
      if (src === null) continue;
      const clean = stripComments(src, '.vue');
      const imports = [...clean.matchAll(/import[^;']*?from\s*'([^']+)'/g)].map((m) => m[1]);
      const renders = rule.marker.filter((m) => imports.some((i) => i.endsWith(m)));
      if (renders.length < rule.markerMin) continue;
      const missing = rule.requires.filter(
        (r) => !imports.some((i) => i.endsWith(r.import) || i.endsWith(r.import.replace(/\.vue$/, ''))),
      );
      surfaces.push({ file: rel, renders, missing: missing.map((m) => m.import) });
      if (missing.length) {
        violations.push({
          file: rel,
          renders,
          missing: missing.map((m) => `${m.import} (${m.concept})`),
        });
      }
    }
    out.push({ id: rule.id, what: rule.what, surfaces, violations });
  }
  return out;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/** A stable key for a finding: the set of files it spans. */
export function findingSignature(finding) {
  return [...new Set(finding.sites.map((s) => s.file))].sort().join(' <> ');
}

export function scan(opts = {}) {
  const t0 = Date.now();
  const cfg = { ...DEFAULTS, ...opts };
  const files = collectFiles(cfg.roots ?? SCAN_ROOTS, cfg.repoRoot ?? REPO_ROOT);
  const stream = buildStream(files);

  const renamedVals = renamedValues(stream);

  const verbatim = findClones({
    values: stream.v,
    shapeValues: renamedVals,
    kinds: stream.t,
    stream,
    k: cfg.minVerbatim,
    maxOcc: cfg.maxOccurrences,
    minShape: cfg.minShapeVerbatim,
  });

  const renamed = findClones({
    values: renamedVals,
    shapeValues: renamedVals,
    kinds: stream.t,
    stream,
    k: cfg.minRenamed,
    maxOcc: cfg.maxOccurrences,
    minShape: cfg.minShapeRenamed,
  });

  const findings = [];
  const seen = new Set();
  const emit = (kind, list) => {
    for (const c of list) {
      const sites = c.sites.map((s) => describeSite(stream, s.start, s.len));
      const f = { kind, tokens: c.tokens, sites };
      // A verbatim clone is also a renamed clone; report it once, as the
      // stronger claim.
      const key = `${findingSignature(f)}|${sites.map((s) => s.startLine).join(',')}`;
      if (seen.has(key)) continue;
      seen.add(key);
      f.lines = Math.max(...sites.map((s) => s.endLine - s.startLine + 1));
      findings.push(f);
    }
  };
  emit('verbatim', verbatim);
  emit('renamed', renamed);

  findings.sort((a, b) => b.tokens - a.tokens);

  const repoRoot = cfg.repoRoot ?? REPO_ROOT;
  const concepts = cfg.skipConcepts ? [] : scanConcepts(repoRoot);
  const composition = cfg.skipConcepts ? [] : scanComposition(repoRoot);

  return {
    generatedAt: new Date().toISOString(),
    config: {
      minVerbatim: cfg.minVerbatim,
      minRenamed: cfg.minRenamed,
      minShapeVerbatim: cfg.minShapeVerbatim,
      minShapeRenamed: cfg.minShapeRenamed,
      maxOccurrences: cfg.maxOccurrences,
      roots: cfg.roots ?? SCAN_ROOTS,
    },
    stats: {
      files: files.length,
      units: stream.units.length,
      tokens: stream.v.length,
      ms: Date.now() - t0,
    },
    findings,
    concepts,
    composition,
  };
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

function main(argv) {
  const opts = {};
  let json = false;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--json') json = true;
    else if (a === '--min-verbatim') opts.minVerbatim = Number(argv[++i]);
    else if (a === '--min-renamed') opts.minRenamed = Number(argv[++i]);
    else if (a === '--min-shape-verbatim') opts.minShapeVerbatim = Number(argv[++i]);
    else if (a === '--min-shape-renamed') opts.minShapeRenamed = Number(argv[++i]);
    else if (a === '--max-occ') opts.maxOccurrences = Number(argv[++i]);
    else if (a === '--only') (opts.roots ??= []).push(argv[++i]);
    else if (a === '--root') opts.repoRoot = path.resolve(argv[++i]);
  }
  const out = scan(opts);
  if (json) {
    process.stdout.write(JSON.stringify(out, null, 2));
    return;
  }
  const { stats, findings, config } = out;
  console.log(
    `dup-scan: ${stats.files} files, ${stats.tokens.toLocaleString('en-US')} tokens, ${stats.ms} ms`,
  );
  console.log(
    `thresholds: verbatim >= ${config.minVerbatim} tokens / ${config.minShapeVerbatim} shape, ` +
      `renamed >= ${config.minRenamed} tokens / ${config.minShapeRenamed} shape`,
  );
  console.log(`\n== duplicated fragments: ${findings.length} ==\n`);
  findings.forEach((f, i) => {
    console.log(`${String(i + 1).padStart(3)}. [${f.kind}] ${f.tokens} tokens`);
    for (const s of f.sites) console.log(`     ${s.file}:${s.startLine}-${s.endLine}`);
    console.log('');
  });

  const strays = out.concepts.filter((c) => c.strays.length);
  console.log(`== concepts implemented outside their home: ${strays.length} ==\n`);
  for (const c of strays) {
    console.log(`  ${c.id} — ${c.what}`);
    console.log(`     home: ${c.home.join(', ')}`);
    for (const s of c.strays) console.log(`     ${s.file}:${s.lines.join(',')}`);
    console.log(`     fix: ${c.fix}\n`);
  }

  const comp = out.composition.flatMap((r) => r.violations.map((v) => ({ rule: r.id, ...v })));
  console.log(`== surfaces that build their own chrome: ${comp.length} ==\n`);
  for (const v of comp) {
    console.log(`  ${v.file} renders ${v.renders.join(', ')}`);
    console.log(`     but does not use: ${v.missing.join(', ')}\n`);
  }

  if (findings.length || strays.length || comp.length) process.exitCode = 1;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main(process.argv.slice(2));
}
