#!/usr/bin/env bash
# Builds a standalone copy of the guest SDK (backend/pkg/pluginkit + wire)
# under the PUBLIC module path, for developing an app plugin before the
# filex release that ships it:
#
#   bash scripts/pluginkit-devmodule.sh /g/filex-sdk-dev
#
# A plugin repository then says, until the release is out:
#
#   require github.com/brf-tech/filex/backend v0.0.0
#   replace github.com/brf-tech/filex/backend => ../filex-sdk-dev
#
# and drops the replace afterwards. The copy is generated, never edited:
# rerun after changing pkg/pluginkit. Import paths are rewritten from the
# private module (github.com/brf-tech/filex/backend) to the public one,
# exactly as scripts/export-public.sh does for the whole tree.
set -euo pipefail
out="${1:?target directory}"
root="$(cd "$(dirname "$0")/.." && pwd)"
priv="github.com/brf-tech/filex/backend"
pub="github.com/brf-tech/filex/backend"
rm -rf "$out"
mkdir -p "$out/pkg"
cp -r "$root/backend/pkg/pluginkit" "$out/pkg/pluginkit"
find "$out/pkg" -name '*_test.go' -delete
find "$out/pkg" -name '*.go' -exec sed -i "s#$priv#$pub#g" {} +
pdk="$(grep -E '^\s*github.com/extism/go-pdk ' "$root/backend/go.mod" | awk '{print $2}')"
gover="$(grep -E '^go ' "$root/backend/go.mod" | awk '{print $2}')"
cat > "$out/go.mod" <<EOF
module $pub

go $gover

require github.com/extism/go-pdk $pdk
EOF
cat > "$out/README.md" <<'EOF'
# filex guest SDK — development copy

Generated by `scripts/pluginkit-devmodule.sh` in the filex repository. Do not
edit; rerun the script. Once the filex release that ships `pkg/pluginkit` is
on GitHub, drop the `replace` in your plugin's go.mod and use the tag.

`sdk-stamp.json` records the pluginkit this copy was generated from, and
`check-sdk.mjs` compares the two and REFUSES a build once they have drifted.
Call it from your plugin's build, before `go build`:

    node ../filex-sdk-dev/check-sdk.mjs || exit 1

It is silent and exits 0 once your go.mod points at the published module
instead of this directory: there is then no local copy to be stale.
EOF
(cd "$out" && GOFLAGS=-mod=mod go mod tidy >/dev/null 2>&1 || true)

# The copy carries its own guard: what pluginkit it came from, and the script
# that refuses a build when that pluginkit has moved on since. An app runs it
# from here, so a THIRD app gets it by pointing its go.mod at this directory
# and adding the one line to its build (see scripts/lib/sdk-check.mjs).
cp "$root/scripts/lib/sdk-check.mjs" "$out/check-sdk.mjs"
node "$out/check-sdk.mjs" --write "$out" "$root/backend/pkg/pluginkit"

echo "dev module at $out ($(find "$out/pkg" -name '*.go' | wc -l) files)"
